<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sUse Cases%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sUse Cases Application%s. '), '<a href="https://github.com/dlabas/UseCasesApplication" target="_blank">', '</a>') ?></p>
    <p><a class="btn btn-success btn-large" href="https://github.com/dlabas/UseCasesApplication" target="_blank"><?php echo $this->translate('Fork Use Cases Application on GitHub') ?> &raquo;</a></p>
</div>